"""add not null constraint

Revision ID: a8b5db702809
Revises: 0bbbabf1fbd9
Create Date: 2023-07-10 23:42:48.034177

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'a8b5db702809'
down_revision = '0bbbabf1fbd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'title',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('items', 'owner_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_index('ix_items_description', table_name='items')
    op.drop_index('ix_items_id', table_name='items')
    op.alter_column('users', 'email',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('users', 'hashed_password',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('users', 'active',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('users', 'admin',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'admin',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('users', 'active',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('users', 'hashed_password',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('users', 'email',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.create_index('ix_items_id', 'items', ['id'], unique=False)
    op.create_index('ix_items_description', 'items',
                    ['description'], unique=False)
    op.alter_column('items', 'owner_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('items', 'title',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###
